### ISSUE TITLE
The path do not have permission for self-hosted macOS runner

### ISSUE THREAD

**Issue by Wei18** [irgaly/setup-mint#23]
https://github.com/irgaly/setup-mint/blob/99eaad2ad1197ea872390322a47620da2f21fde4/src/main.ts#L72

**Comment by irgaly** [comment]
Thank you reporting 👍 
I see, I will support self hosted runner.

**Comment by Wei18** [comment]
Thanks

**Comment by irgaly** [comment]
* #24

setup-mint v1.5.0 installs mint to `$HOME/bin/mint` now. Please check latest version by `setup-mint@v1` that automatically point to v1.5.0 tag.

**Comment by r-plus** [comment]
Hi

`$HOME/bin` is not contain in default `$PATH` of linux(ubuntu) github actions runner.
So we see the `mint` not found error since v1.5.0.

**Comment by irgaly** [comment]
@r-plus 

Sorry, v1.5.0 have a break change as you noticed.
I'll revert v1.5.0 change, and produce new option to specify mint executable path for this issue's other solution.

**Comment by irgaly** [comment]
@r-plus 

I have released v1.6.0, this will install mint to `/usr/local/bin/mint` again. `setup-mint@v1` will automatically use v1.6.0. Please try this release.

https://github.com/irgaly/setup-mint/releases/tag/v1.6.0

**Comment by irgaly** [comment]
@r-plus 
Nice try! Thank you for the information. I'm relieved to hear that 😄
